name: Bug Report
description: File a bug report
title: '[BUG]: '
labels:
  - bug
assignees: []
body:
  - type: markdown
    attributes:
      value: >-
        ## Bug Report

        Thank you for taking the time to report a bug. Please fill out this form
        and include as much information as possible.
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the project are you using?
      placeholder: 'e.g., 0.7.6'
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Briefly describe the bug.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: Please provide detailed steps for reproducing the issue.
      placeholder: |-
        Step 1: ...
        Step 2: ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: Please describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: >-
        Please provide any relevant logs or screenshots to help understand the
        issue.
  - type: markdown
    attributes:
      value: |-
        ## Additional context
        Provide any additional context or information.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
